Attempt to fix run condition:
Some of the mp tests were failing like this:

tests/test_broker.py::test_mp_checkout FAILED                                                                                                                                          [ 50%]
tests/test_broker.py::test_mp_checkout_twice PASSED                                                                                                                                    [ 60%]
tests/test_broker.py::test_mp_decorator PASSED                                                                                                                                         [ 70%]
tests/providers/test_ansible_tower.py::test_exec_workflow PASSED                                                                                                                       [ 80%]
tests/providers/test_ansible_tower.py::test_host_creation PASSED                                                                                                                       [ 90%]
tests/providers/test_ansible_tower.py::test_workflow_lookup_failure PASSED                                                                                                             [100%]

========================================================================================== FAILURES ==========================================================================================
______________________________________________________________________________________ test_mp_checkout ______________________________________________________________________________________
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/jhenner/work/sat/broker/broker/broker.py", line 116, in _checkout
    helpers.update_inventory(add=host.to_dict())
  File "/home/jhenner/work/sat/broker/broker/helpers.py", line 154, in update_inventory
    inventory_file.unlink()  # This making mp tests to fail. Perhaps a race condition.
  File "/usr/lib64/python3.9/pathlib.py", line 1340, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: 'inventory.yaml'
"""

The above exception was the direct cause of the following exception:

    def test_mp_checkout():
        """Test that broker can checkout multiple hosts using multiprocessing"""
        broker_inst = broker.VMBroker(nick="test_nick", _count=2)
>       broker_inst.checkout()

tests/test_broker.py:50:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
broker/broker.py:126: in checkout
    hosts = self._checkout(connect=connect)
broker/broker.py:62: in mp_split
    results.extend(f.result())
/usr/lib64/python3.9/concurrent/futures/_base.py:433: in result
    return self.__get_result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Future at 0x7f4c662e9790 state=finished raised FileNotFoundError>

    def __get_result(self):
        if self._exception:
>           raise self._exception
E           FileNotFoundError: [Errno 2] No such file or directory: 'inventory.yaml'

It seem sto be a run condition when working with the inventory file.
Fixing by moving the work with the inventory out of the concurrently
executed code.